---
title: "A Gapminder exploration"
output: pdf_document
---
```{r package_setup, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

knitr::opts_chunk$set(
  fig.width = 12,   # increase width
  fig.height = 6,
  out.width = "100%"   # VERY IMPORTANT
)

library(tidyr)
library(readr)
library(dplyr)
```
```{r}
read_csv_locale <- function(file, ...) {
  readr::read_csv(
    file = file,
    locale = readr::locale(decimal_mark = ".", grouping_mark = ","),
    show_col_types = FALSE,
    ...
  )
}
```

# Data loading
```{r}
t.features = read_csv_locale('data/gapminder-collated.csv')
t.countries = read_csv_locale('data/gapminder-countries.csv')

t.all = left_join(t.features, t.countries, by='country')

col.features = colnames(t.features)[seq(3, ncol(t.features), by=2)]
```
Gapminder data were loaded from [Gapminder](https://www.gapminder.org/data/), avaliable (observations and forecast) from `r length(unique(t.all$country))` countries.
Available features are:

```{r}
t.feature_ranges <- {
  t_values <- t.features %>%
    pivot_longer(
      cols = -c(country, time),
      names_to = "feature",
      values_to = "value"
    ) %>%
    filter(!grepl("_is_forecast$", feature))

  t_flags <- t.features %>%
    pivot_longer(
      cols = ends_with("_is_forecast"),
      names_to = "feature",
      values_to = "is_forecast"
    ) %>%
    mutate(
      feature = sub("_is_forecast$", "", feature),
      is_forecast = is_forecast %in% c(TRUE, "True", "TRUE", "true")
    )

  t_values %>%
    select(country, time, feature) %>%
    left_join(t_flags, by = c("country", "time", "feature")) %>%
    mutate(is_forecast = coalesce(is_forecast, FALSE)) %>%
    group_by(feature) %>%
    summarise(
      name = first(feature),
      start_observation = min(time[!is_forecast], na.rm = TRUE),
      start_forecast = if (any(is_forecast)) min(time[is_forecast], na.rm = TRUE) else NA_real_,
      end_forecast = if (any(is_forecast)) max(time[is_forecast], na.rm = TRUE) else NA_real_,
      .groups = "drop"
    ) %>%
    select(name, start_observation, start_forecast, end_forecast)
}

knitr::kable(
        t.feature_ranges,
        col.names = c('feature', 'recorded from', 'forecasted from', 'until')
)
```

